[project]
name = "mcm-2026-lly"
version = "0.1.0"
description = "MCM 2026 Problem C - DWTS Fan Vote Estimation"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "numpy>=2.0",
    "polars>=1.0",
    "matplotlib>=3.9",
    "scipy>=1.14",
    "pandas>=3.0.0",
    "statsmodels>=0.14.6",
    "seaborn>=0.13.2",
    "pyarrow>=23.0.0",
]

[dependency-groups]
dev = [
    "ruff>=0.14.14",
]
